//===----------------------------------------------------------------------===//
//
// This source file is part of the AsyncHTTPClient open source project
//
// Copyright (c) 2018-2019 Apple Inc. and the AsyncHTTPClient project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of AsyncHTTPClient project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// AsyncRequestTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension AsyncRequestTests {
    static var allTests: [(String, (AsyncRequestTests) -> () throws -> Void)] {
        return [
            ("testCancelAsyncRequest", testCancelAsyncRequest),
            ("testResponseStreamingWorks", testResponseStreamingWorks),
            ("testWriteBackpressureWorks", testWriteBackpressureWorks),
            ("testSimpleGetRequest", testSimpleGetRequest),
            ("testBiDirectionalStreamingHTTP2", testBiDirectionalStreamingHTTP2),
        ]
    }
}
