//===----------------------------------------------------------------------===//
//
// This source file is part of the AsyncHTTPClient open source project
//
// Copyright (c) 2018-2019 Apple Inc. and the AsyncHTTPClient project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of AsyncHTTPClient project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// ConnectionPoolTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension ConnectionPoolTests {
    static var allTests: [(String, (ConnectionPoolTests) -> () throws -> Void)] {
        return [
            ("testPending", testPending),
            ("testAcquireWhenEmpty", testAcquireWhenEmpty),
            ("testAcquireWhenAvailable", testAcquireWhenAvailable),
            ("testAcquireWhenUnavailable", testAcquireWhenUnavailable),
            ("testAcquireWhenEmptySpecificEL", testAcquireWhenEmptySpecificEL),
            ("testAcquireWhenAvailableSpecificEL", testAcquireWhenAvailableSpecificEL),
            ("testAcquireReplace", testAcquireReplace),
            ("testAcquireWhenUnavailableSpecificEL", testAcquireWhenUnavailableSpecificEL),
            ("testAcquireWhenClosed", testAcquireWhenClosed),
            ("testConnectFailedWhenClosed", testConnectFailedWhenClosed),
            ("testReleaseAliveConnectionEmptyQueue", testReleaseAliveConnectionEmptyQueue),
            ("testReleaseAliveButClosingConnectionEmptyQueue", testReleaseAliveButClosingConnectionEmptyQueue),
            ("testReleaseInactiveConnectionEmptyQueue", testReleaseInactiveConnectionEmptyQueue),
            ("testReleaseInactiveConnectionEmptyQueueHasConnections", testReleaseInactiveConnectionEmptyQueueHasConnections),
            ("testReleaseAliveConnectionHasWaiter", testReleaseAliveConnectionHasWaiter),
            ("testReleaseInactiveConnectionHasWaitersNoConnections", testReleaseInactiveConnectionHasWaitersNoConnections),
            ("testReleaseAliveConnectionSameELHasWaiterSpecificEL", testReleaseAliveConnectionSameELHasWaiterSpecificEL),
            ("testReleaseAliveConnectionDifferentELNoSameELConnectionsOnLimitHasWaiterSpecificEL", testReleaseAliveConnectionDifferentELNoSameELConnectionsOnLimitHasWaiterSpecificEL),
            ("testNextWaiterEmptyQueue", testNextWaiterEmptyQueue),
            ("testNextWaiterEmptyQueueHasConnections", testNextWaiterEmptyQueueHasConnections),
            ("testTimeoutLeasedConnection", testTimeoutLeasedConnection),
            ("testTimeoutAvailableConnection", testTimeoutAvailableConnection),
            ("testRemoteClosedLeasedConnection", testRemoteClosedLeasedConnection),
            ("testRemoteClosedAvailableConnection", testRemoteClosedAvailableConnection),
            ("testShutdownOnPendingAndSuccess", testShutdownOnPendingAndSuccess),
            ("testShutdownOnPendingAndError", testShutdownOnPendingAndError),
            ("testShutdownTimeout", testShutdownTimeout),
            ("testShutdownRemoteClosed", testShutdownRemoteClosed),
        ]
    }
}
