//===----------------------------------------------------------------------===//
//
// This source file is part of the AsyncHTTPClient open source project
//
// Copyright (c) 2018-2019 Apple Inc. and the AsyncHTTPClient project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of AsyncHTTPClient project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// HTTP2ClientRequestHandlerTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension HTTP2ClientRequestHandlerTests {
    static var allTests: [(String, (HTTP2ClientRequestHandlerTests) -> () throws -> Void)] {
        return [
            ("testResponseBackpressure", testResponseBackpressure),
            ("testWriteBackpressure", testWriteBackpressure),
            ("testIdleReadTimeout", testIdleReadTimeout),
            ("testIdleReadTimeoutIsCanceledIfRequestIsCanceled", testIdleReadTimeoutIsCanceledIfRequestIsCanceled),
            ("testWriteHTTPHeadFails", testWriteHTTPHeadFails),
        ]
    }
}
