version: "3"

services:

  runtime-setup:
    image: async-http-client:20.04-5.5
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.5"

  test:
    image: async-http-client:20.04-5.5
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: async-http-client:20.04-5.5
