version: "3"

services:
        
  runtime-setup:
    image: async-http-client:20.04-5.5
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.5-focal"
        

  test:
    image: async-http-client:20.04-5.5
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: async-http-client:20.04-5.5
