version: "3"

services:

  runtime-setup:
    image: async-http-client:18.04-5.4
    build:
      args:
        ubuntu_version: "bionic"
        swift_version: "5.4"

  test:
    image: async-http-client:18.04-5.4
    command: /bin/bash -xcl "swift test --parallel -Xswiftc -warnings-as-errors $${SANITIZER_ARG-}"
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: async-http-client:18.04-5.4
