version: "3"

services:

  runtime-setup:
    image: async-http-client:22.04-5.10
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.10"

  documentation-check:
    image: async-http-client:22.04-5.10

  test:
    image: async-http-client:22.04-5.10
    environment:
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: async-http-client:22.04-5.10
