//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIOHTTPClient open source project
//
// Copyright (c) 2018-2019 Swift Server Working Group and the SwiftNIOHTTPClient project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIOHTTPClient project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// SwiftNIOHTTPTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension SwiftHTTPTests {
    static var allTests: [(String, (SwiftHTTPTests) -> () throws -> Void)] {
        return [
            ("testRequestURI", testRequestURI),
            ("testHTTPPartsHandler", testHTTPPartsHandler),
            ("testHTTPPartsHandlerMultiBody", testHTTPPartsHandlerMultiBody),
            ("testGet", testGet),
            ("testPost", testPost),
            ("testGetHttps", testGetHttps),
            ("testPostHttps", testPostHttps),
            ("testHttpRedirect", testHttpRedirect),
            ("testHttpHostRedirect", testHttpHostRedirect),
            ("testMultipleContentLengthHeaders", testMultipleContentLengthHeaders),
            ("testStreaming", testStreaming),
            ("testRemoteClose", testRemoteClose),
            ("testReadTimeout", testReadTimeout),
            ("testCancel", testCancel),
            ("testProxyPlaintext", testProxyPlaintext),
            ("testProxyTLS", testProxyTLS),
            ("testUploadStreaming", testUploadStreaming),
            ("testProxyStreaming", testProxyStreaming),
        ]
    }
}
